[package]
name = "fingerprint-h2"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
authors.workspace = true

[dependencies]
fingerprint-core = { version = "0.1.0", path = "../fingerprint-core" }
fluke-hpack = "0.3.1"
thiserror = "2.0.20"

[dev-dependencies]
proptest = "1.9.0"
